config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("restaurants/", include("restaurants.urls", namespace="restaurants")),
    path("users/", include("users.urls", namespace="users")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("youcandoit/", admin.site.urls),
    path("sentry-debug/", trigger_error),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from restaurants import views as restaurant_views
from django.views.generic import TemplateView

app_name = "core"
# include() 안에 namespace 를 사용하면 app_name 을 지정해 줘야 한다.(namespace = app_name)

urlpatterns = [
    path("", restaurant_views.main_views, name="home"),
    path(
        'robots.txt/',
        TemplateView.as_view(
            template_name="robots.txt", content_type='text/plain')),
    path(
        'ads.txt/',
        TemplateView.as_view(
            template_name="ads.txt", content_type='text/plain')),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path(
        "toggle/<int:restaurant_pk>/", views.toggle_restaurant, name="toggle-restaurant"
    ),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

restaurants/urls.py
from django.urls import path
from . import views

app_name = "restaurants"

urlpatterns = [
    path("<int:pk>/", views.RestaurantDetail.as_view(), name="detail"),
    path("search/", views.search, name="search"),
    path("search-channels/", views.search_channels, name="search-channels"),
    path("channel/", views.channel_view, name="channels"),
    path("channel/<str:verb>/", views.channel_search, name="channel"),
    path("category/<str:verb>/", views.category_search, name="category"),
    path(
        'r_upload-with-csv/', views.restaurant_upload,
        name="restaurant-upload"),
    path('y_upload-with-csv/', views.youtube_upload, name="youtube-upload"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
]

templates/partials/adsense_content.html
<div align="center" class="py-10 w-11/12 lg:w-3/5 mb-20">
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
     <ins class="adsbygoogle"
          style="display:block; text-align:center;"
          data-ad-layout="in-article"
          data-ad-format="fluid"
          data-ad-client="ca-pub-3931834768948104"
          data-ad-slot="2443560930"></ins>
     <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
     </script>
</div>

templates/partials/adsense_horizontal.html
<div align="center" class="py-10">
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- amatna_horizontal -->
    <ins class="adsbygoogle"
         style="display:block"
         data-ad-client="ca-pub-3931834768948104"
         data-ad-slot="9354540521"
         data-ad-format="horizontal"
         data-full-width-responsive="true"></ins>
    <script>
         (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
</div>

templates/partials/footer.html
{% load i18n %}
<footer class="mx-auto text-center py-10 border-t font-medium bg-gray-600">
    <div class="flex flex-col">
        <span class="text-red-100 sm:text-lg mb-2">
            {% trans "Please don't copy us." %}
        </span>
        <span class="text-sm sm:text-lg text-gray-400">&copy;{% trans "Amatna : All rights reserved" %}</span>
    </div>

</footer>

templates/partials/messages.html
{% if messages %}
<ul class="absolute mx-auto top-0 left-0 right-0 flex justify-center">
    {% for message in messages %}
        <li class="message font-medium sm:w-1/4 w-5/6 bg-gray-700 z-10 rounded-lg text-sm sm:text-base text-white py-4 px-6 text-center {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
        <!-- css를 위해서 이렇게 수정 -->
    {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
{% load i18n %}
<ul class="flex items-center text-xs sm:text-sm font-medium h-full align-baseline ">

    <li class="nav_link truncate "><a href="{% url "restaurants:channels" %}">{% trans 'Channel lists' %}</a></li>
    {% if user.is_authenticated %}
        <li class="nav_link mr-1 sm:mr-2 truncate">
            <a href="{% url "lists:see-favs" %}">{% trans 'Favorite' %}
                {% if user.list.restaurants.count > 0 %}
                    <span class="ml-0 sm:ml-1 px-2 py-1 rounded-xl bg-teal-500 text-white">{{user.list.restaurants.count}}</span>
                {% endif %}
            </a>
        </li>
        <li>
            <a href="{{user.get_absolute_url}}">            
                <div class="flex flex-row items-center border-gray-200 border shadow rounded-xl p-2 hover:shadow-lg -mr-2">
                    <span class="mr-2 truncate">{{user.nickname}}</span>
                    {% if user.avatar %}
                        <div class="h-6 sm:h-8 w-6 sm:w-8 rounded-full bg-cover" style="background-image: url({{user.avatar.url}})">
                    {% else %}
                        <div class="h-6 sm:h-8 w-6 sm:w-8 bg-gray-700 rounded-full flex justify-center items-center">
                            <span class="text-sm sm:text-lg font-medium text-white">{{user.nickname|first}}</span>     
                    {% endif %}
                    </div>
                </div>
            </a>
        </li>
        
    {% else %}
        <li class="nav_link mr-2 truncate"><a href="{% url "users:login" %}">{% trans 'Log in' %}</a></li>
        <li class="nav_link hover:bg-white border hover:shadow-lg shadow rounded-xl truncate -mr-2"><a href="{% url "users:signup" %}">{% trans 'Sign up' %}</a></li>

    {% endif %}
</ul>

templates/partials/search_bar.html
{% load i18n %}

<form method="get" action="{% url 'restaurants:search' %}" class="w-full">
    <input 
        class="search-box border px-5 text-gray-900 placeholder-gray-600 font-medium py-3 rounded-sm shadow-md hover:shadow-lg " 
        name="tag_set" 
        placeholder="{% trans 'Search by menu or area' %}" 
    />
</form>

templates/partials/social_login.html
{% load i18n %}

<div class="flex flex-col w-full"> 
    <a href="{% url 'users:kakao-login' %}" class="btn border text-yellow-800 mb-2 border-yellow-400 bg-yellow-400">
        <i class="fas fa-comment mr-2 fa-lg text-orange-900"></i>{% trans 'Continue with Kakao' %}
    </a>
</div>

<div class="flex items-center w-full my-10">
    <div class="h-px w-full bg-gray-400"></div> 
    <span class="text-gray-600 font-midium px-5 text-sm block">or</span>
    <div class="h-px w-full bg-gray-400"></div>
</div>