config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("restaurants/", include("restaurants.urls", namespace="restaurants")),
    path("users/", include("users.urls", namespace="users")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("youcandoit/", admin.site.urls),
    path("sentry-debug/", trigger_error),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from restaurants import views as restaurant_views
from django.views.generic import TemplateView

app_name = "core"
# include() 안에 namespace 를 사용하면 app_name 을 지정해 줘야 한다.(namespace = app_name)

urlpatterns = [
    path("", restaurant_views.main_views, name="home"),
    path(
        'robots.txt/',
        TemplateView.as_view(
            template_name="robots.txt", content_type='text/plain')),
    path(
        'ads.txt/',
        TemplateView.as_view(
            template_name="ads.txt", content_type='text/plain')),
]

restaurants/urls.py
from django.urls import path
from . import views

app_name = "restaurants"

urlpatterns = [
    path("<int:pk>/", views.RestaurantDetail.as_view(), name="detail"),
    path("search/", views.search, name="search"),
    path("search-channels/", views.search_channels, name="search-channels"),
    path("channel/", views.channel_view, name="channels"),
    path("channel/<str:verb>/", views.channel_search, name="channel"),
    path("category/<str:verb>/", views.category_search, name="category"),
    path(
        'r_upload-with-csv/', views.restaurant_upload,
        name="restaurant-upload"),
    path('y_upload-with-csv/', views.youtube_upload, name="youtube-upload"),
]

templates/mixins/categories.html
<a href="{% url 'restaurants:category' c.name %}" >
    <span class="inline-block bg-yellow-400 text-sm sm:text-base font-medium px-4 py-2 my-1 mr-2 rounded-full hover:opacity-50">{{c}}</span>
</a>   

templates/mixins/channel_card.html
{% load i18n static %}
<div class="w-1/2 md:w-1/4 mb-8 p-2 md:p-3">
    <a href="{% url 'restaurants:channel' channel.name %}">
        <div class="w-full h-48 lg:h-25vh bg-cover bg-center rounded-lg mb-2 flex  justify-end" style="background-image: url({{channel.image.url}});">
        </div>
    </a>

    <a href="{% if channel.youtube_link %}https://www.youtube.com/channel/{{channel.youtube_link}}{% elif channel.instagram_link %}https://www.instagram.com/{{channel.instagram_link}}{% else %}{% url 'restaurants:channel' channel.name %}{% endif %}" target="_blank">        
        <div class="w-full flex justify-between mb-2 items-center">
            <img src="{% if channel.youtube_link %}{% static 'img/youtube_logo.png' %}{% elif channel.instagram_link %}{% static 'img/instagram_logo.png' %}{% else %}{{channel.thumbnail.url}}{% endif %}" class="h-8 w-8 md:h-16 md:w-16 border-gray-200 border rounded-lg"/>
            <div class="flex justify-between ml-1 md:ml-3 w-4/5 items-center">
                <span class="text-sm md:text-base text-black font-medium">{{channel.name}}</span>             
                <span class="text-xs md:text-sm text-red-400 mr-1 font-normal truncate block ">
                    {% if channel.youtube_link %}
                        {% trans 'visit youtube' %}
                    {% elif channel.instagram_link %}
                        {% trans 'visit instagram' %}
                    {% endif %}
                </span>
            </div>
        </div>    
    </a>
    <a href="{% url 'restaurants:channel' channel.name %}">
        <div>
            <div class="text-xs md:text-sm m-2">
               {{channel.description}}
            </div>
            <div class="text-xs md:text-sm text-right text-blue-400 mr-3">
                {% trans 'view more >' %}
            </div>
        </div>
    </a>
</div>

templates/mixins/map_marker.html
{% load static i18n %}
<script>
    var restaurants_string = `{% for restaurant in restaurants.object_list %}` 
                           + `{"id":{{restaurant.id}},"title":"{{restaurant.title}}","x":{{restaurant.x}},"y":{{restaurant.y}},"address":"{{restaurant.address}}","phone_number":"{{restaurant.phone_number}}","category":"{% for category in restaurant.category.all %}{{category}},{% endfor %}"},`
                           + `{% endfor %}`
    var restaurants_json = `[` + restaurants_string.slice(0,-1) + ']'
    restaurants = JSON.parse(restaurants_json)
    var icon_src = `{% static "img/marker.png" %}`
    var markerImage = new kakao.maps.MarkerImage(icon_src, new kakao.maps.Size(31, 35))

    var mapContainer = document.getElementById('map'),
        mapOption = { 
            center: new kakao.maps.LatLng(restaurants[0].y, restaurants[0].x),
            level: 7
        };
    
    var map = new kakao.maps.Map(mapContainer, mapOption);
    var bounds = new kakao.maps.LatLngBounds();

    for (var i = 0; i < restaurants.length; i ++) {
        // 마커를 생성합니다
        var id = restaurants[i].id
        var title = restaurants[i].title
        var address = restaurants[i].address
        var phone_number = restaurants[i].phone_number
        var category = restaurants[i].category.slice(0,-1)
        
        var latlng = new kakao.maps.LatLng(restaurants[i].y, restaurants[i].x)
        var content = `<div class="h-20 w-48 bg-red-100 rounded-lg">`
                    + `     <a href="https://amatna.net/restaurants/${id}">`
                    + `         <div class="arrow_box flex flex-col px-2 py-2">`
                    + `             <div class="text-sm border-b border-gray-600 pb-1 text-red-500 font-normal w-full mb-1 truncate">${i+1}. ${title} <span class="text-xs font-normal text-gray-600 text-center "> | ${category} </div>`
                    + `             <span class="text-xs truncate">${address}</span>`
                    + `             <span class="text-xs">${phone_number}</span>`
                    + `         </div>`
                    + `     </a>`
                    + `</div>`
        var marker = new kakao.maps.Marker({
            map: map,
            position: latlng,
            image : markerImage,
            clickable: true
        });
        bounds.extend(latlng);
        kakao.maps.event.addListener(marker, 'click', makeClickListener(map, marker, content, latlng));
        kakao.maps.event.addListener(marker, 'mouseover', makeMouseOverListener(map, marker, content, latlng));
    }    

    var customOverlay = new kakao.maps.CustomOverlay({
        content: content,
        position: latlng,
        xAnchor: 0.5,
        yAnchor: 1.7
    });

    function makeMouseOverListener(map, marker, content=content, position=latlng) {
        return function() {
            customOverlay.setPosition(position)
            customOverlay.setContent(content)
            customOverlay.setMap(map, marker);
        };
    }    

    function makeClickListener(map, marker, content=content, position=latlng) {
        return function() {
            customOverlay.setPosition(position)
            customOverlay.setContent(content)
            customOverlay.setMap(map, marker);
        };
    }    

    function setBounds() {
        map.setBounds(bounds);
    }

    function getLocation(){
        if (navigator.geolocation) {
    
            // GeoLocation을 이용해서 접속 위치를 얻어옵니다
            navigator.geolocation.getCurrentPosition(function(position) {
                
                var lat = position.coords.latitude, // 위도
                    lon = position.coords.longitude; // 경도

                var locPosition = new kakao.maps.LatLng(lat, lon) // 마커가 표시될 위치를 geolocation으로 얻어온 좌표로 생성합니다
                getLocationMarker(locPosition)
            });
            
        } else { // HTML5의 GeoLocation을 사용할 수 없을때 마커 표시 위치와 인포윈도우 내용을 설정합니다
            alert("아!맛나 : 위치를 가져 올 수 없는 브라우저 입니다.")
        }
        
    }

    function getLocationMarker(locPosition){
        var map_pin_src = `{% static "img/map_pin.png" %}`
        var content = `<div class="font-normal text-sm px-1 bg-gray-100 rounded-sm">{% trans 'My Location' %}`
                    + `</div>`        
        var mapPinImage = new kakao.maps.MarkerImage(map_pin_src, new kakao.maps.Size(30, 30))
        var marker = new kakao.maps.Marker({
            map: map,
            position: locPosition,
            image: mapPinImage,
        })

        var customOverlay = new kakao.maps.CustomOverlay({
            content: content,
            position: locPosition,
            xAnchor: 0.5,
            yAnchor: 2.6
        });

        customOverlay.setMap(map);
        map.setCenter(locPosition);    
        map.setLevel(6);
    }
</script>

templates/mixins/no_results.html
{% load i18n static %}
<div class="w-11/12 sm:w-1/3">
    <a href="mailto:furtherdream.ceo@gmail.com?subject=맛집 목록을 만들고 싶은 크리에이터를 추천합니다.">
        <img src="{% static 'img/eating_show_ha.png' %}" class="mt-20 rounded-t-lg w-full">
        <div class="bg-teal-500 py-5 rounded-b-lg text-white text-base sm:text-lg md:text-xl w-full text-center mb-6 p-2">{% trans 'Please recommend your favorite creator.' %}</div>
    </a>
    <a href="{% url 'core:home' %}">
        <div class="bg-red-500 py-5 mb-8 rounded-md w-full text-white text-xl text-center">{% trans 'Back to home' %}</div>
    </a>
</div>

templates/mixins/restaurant_card.html
<div class="w-1/2 md:w-1/4 mb-0 p-3 md:p-4">
    
    <div class="bg-white rounded-lg shadow-2xl">
        <a href="{% url 'restaurants:detail' restaurant.pk %}" class="flex flex-col pb-6 md:pb-12 justify-center items-center">   
            <iframe 
                id="ytplayer" 
                type="text/html" 
                width="300" 
                height="200"
                src="https://www.youtube.com/embed/{{youtube.video_id}}?autoplay=1?modestbranding=1"
                frameborder="0"
                class=" rounded-t-lg w-full mb-4 md:mb-8 h-32 lg:h-25vh"
            ></iframe>
            <div class="text-sm md:text-base text-gray-800 w-5/6">{{youtube.name}}</div>
            
            <span class="font-bold text-lg md:text-2xl text-gray-800 p-3 md:p-6 mb-2 md:mb-4">{{restaurant.title}}
            </span> 
            
            <div class="w-11/12">
                {% include 'mixins/tag.html' with restaurant=restaurant %}
            </div>
        </a>   
    </div>
</div>

templates/mixins/tag.html
<div class="table-row">                  
    {% for t in restaurant.tag_set.all %}
    <form class="inline" mehtod="get" action="{% url 'restaurants:search' %}">
        <button class="tag outline-none" name="tag_set" type="submit" value="{{t.name}}">
            {{t.name}}
        </button>
    </form>
    {% endfor %}
</div>

templates/mixins/user_avatar.html
{% if user_obj.avatar %}
    <div class="{{h_and_w|default:'h-20 w-20'}} rounded-full bg-cover" style="background-image: url({{user.avatar.url}})">
{% else %}
    <div class="{{h_and_w|default:'h-20 w-20'}} bg-gray-700 rounded-full flex justify-center items-center">
        <span class="{{text|default:'text-3xl'}} font-medium text-white">{{user.nickname|first}}</span>
    {% endif %}      
</div> 