config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("restaurants/", include("restaurants.urls", namespace="restaurants")),
    path("users/", include("users.urls", namespace="users")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("youcandoit/", admin.site.urls),
    path("sentry-debug/", trigger_error),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from restaurants import views as restaurant_views
from django.views.generic import TemplateView

app_name = "core"
# include() 안에 namespace 를 사용하면 app_name 을 지정해 줘야 한다.(namespace = app_name)

urlpatterns = [
    path("", restaurant_views.main_views, name="home"),
    path(
        'robots.txt/',
        TemplateView.as_view(
            template_name="robots.txt", content_type='text/plain')),
    path(
        'ads.txt/',
        TemplateView.as_view(
            template_name="ads.txt", content_type='text/plain')),
]

restaurants/urls.py
from django.urls import path
from . import views

app_name = "restaurants"

urlpatterns = [
    path("<int:pk>/", views.RestaurantDetail.as_view(), name="detail"),
    path("search/", views.search, name="search"),
    path("search-channels/", views.search_channels, name="search-channels"),
    path("channel/", views.channel_view, name="channels"),
    path("channel/<str:verb>/", views.channel_search, name="channel"),
    path("category/<str:verb>/", views.category_search, name="category"),
    path(
        'r_upload-with-csv/', views.restaurant_upload,
        name="restaurant-upload"),
    path('y_upload-with-csv/', views.youtube_upload, name="youtube-upload"),
]

restaurants/views.py
import io
import csv
from django.shortcuts import render, reverse
from django.views.generic import DetailView
from django.core.paginator import Paginator
from django.views.generic.edit import FormMixin
from reviews import forms as review_forms
from django.contrib import messages
from . import models


def main_views(request):
    channel_ranked = models.Channel.objects.all().order_by("rank")[0:8]
    all_categories = models.Category.objects.all().order_by("created")
    page = request.GET.get("page")
    all_restaurant = models.Restaurant.objects.all().order_by("-created")[0:80]
    paginator = Paginator(all_restaurant, 16)
    restaurants = paginator.get_page(page)
    return render(
        request,
        "restaurants/main.html",
        context={
            "channels": channel_ranked,
            "restaurants": restaurants,
            "all_categories": all_categories,
        },
    )


def channel_view(request):
    page = request.GET.get("page")
    all_channel = models.Channel.objects.all().order_by("-created")
    paginator = Paginator(all_channel, 16)
    channels = paginator.get_page(page)
    return render(
        request,
        "restaurants/channel_view.html",
        {"channels": channels},
    )


class RestaurantDetail(DetailView, FormMixin):
    """ Restaurant Detail Definition """

    model = models.Restaurant
    form_class = review_forms.CreateReviewForm

    def get_success_url(self):
        return reverse("restaurants:detail", kwargs={"pk": self.object.id})

    def get_context_data(self, **kwargs):
        context = super(RestaurantDetail, self).get_context_data(**kwargs)
        context["form"] = review_forms.CreateReviewForm()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super(RestaurantDetail, self).form_valid(form)


def search_channels(request):
    channel_name = request.GET.get("keyword")
    page = request.GET.get("page")
    qs = models.Channel.objects.filter(name__contains=channel_name)
    paginator = Paginator(qs, 40)
    channels = paginator.get_page(page)
    return render(
        request,
        "restaurants/channel_view.html",
        {
            "channels": channels,
            "channel_name": channel_name
        },
    )


def search(request):
    tag = request.GET.get("tag_set")
    page = request.GET.get("page")
    qs = models.Restaurant.objects.filter(
        tag_set__name=tag).order_by("-created")
    paginator = Paginator(qs, 100)
    restaurants = paginator.get_page(page)
    return render(
        request,
        "restaurants/search.html",
        {
            "tag": tag,
            "restaurants": restaurants
        },
    )


def channel_search(request, verb):
    channel = models.Channel.objects.get(name=verb)
    page = request.GET.get("page")
    qs = models.Restaurant.objects.filter(
        channel__name=verb).order_by("-created")
    paginator = Paginator(qs, 100)
    restaurants = paginator.get_page(page)
    return render(
        request,
        "restaurants/search.html",
        {
            "channel": channel,
            "restaurants": restaurants
        },
    )


def category_search(request, verb):
    all_categories = models.Category.objects.all().order_by("created")
    category = models.Category.objects.get(name=verb)
    page = request.GET.get("page")
    qs = models.Restaurant.objects.filter(
        category__name=verb).order_by("-created")
    paginator = Paginator(qs, 100)
    restaurants = paginator.get_page(page)
    return render(
        request,
        "restaurants/search.html",
        {
            "category": category,
            "restaurants": restaurants,
            "all_categories": all_categories,
        },
    )


def restaurant_upload(request):
    # declaring template
    template = "restaurants/restaurant_upload.html"
    prompt = {
        "order":
            "Order of the CSV should be name, blog_count, biztel, address, menu_list"
    }
    # GET request returns the value of the data with the specified key.
    if request.method == "GET":
        return render(request, template, prompt)
    csv_file = request.FILES['file']
    # let's check if it is a csv file
    if not csv_file.name.endswith('.csv'):
        messages.error(request, 'THIS IS NOT A CSV FILE')
    data_set = csv_file.read().decode('UTF-8')
    # setup a stream which is when we loop through each line
    # we are able to handle a data in a stream
    io_string = io.StringIO(data_set)
    next(io_string)
    for column in csv.reader(io_string, delimiter=',', quotechar='"'):
        restaurant, created = models.Restaurant.objects.update_or_create(
            title=column[0],
            blog_count=column[1],
            phone_number=column[2],
            address=column[3],
            menu=column[4],
            tv_list=column[5],
            naver_place_id=column[6],
            price=column[9],
            biztime_start=column[10],
            biztime_end=column[11],
            biztime_desc=column[12],
            breaktime=column[13],
            holiday=column[14],
            info=column[15],
            comment=column[16],
        )
        restaurant.save()
        channel = models.Channel.objects.filter(name=column[7])
        for id in channel:
            restaurant.channel.add(id)
        youtube = models.Youtube.objects.filter(video_id=column[8])
        for id in youtube:
            restaurant.youtube.add(id)
        category = models.Category.objects.filter(name=column[17])
        for id in category:
            restaurant.category.add(id)

    return render(request, template)


def youtube_upload(request):
    # declaring template
    template = "restaurants/youtube_upload.html"
    # prompt is a context variable that can have different values
    # depending on their context
    prompt = {"order": "Order of the CSV should be name, title, video_id"}
    # GET request returns the value of the data with the specified key.
    if request.method == "GET":
        return render(request, template, prompt)
    csv_file = request.FILES['file']
    # let's check if it is a csv file
    if not csv_file.name.endswith('.csv'):
        messages.error(request, 'THIS IS NOT A CSV FILE')
    data_set = csv_file.read().decode('UTF-8')
    # setup a stream which is when we loop through each line
    # we are able to handle a data in a stream
    io_string = io.StringIO(data_set)
    next(io_string)
    for column in csv.reader(io_string, delimiter=',', quotechar='"'):
        youtube, created = models.Youtube.objects.update_or_create(
            video_id=column[0],
            name=column[1],
        )

    return render(request, template)

templates/restaurants/channel_list.html
{% load i18n %}
{% block content %} 


<div class="bg-gray-100 -mt-8 sm:-mt-4 w-full">
    <div class="justify-between flex flex-row items-center">

      <div class=" pt-12 mb-10 flex flex-col">
        <span class="article_title">{% trans 'DO NOT pay your time for searching restaurant in Korea' %}</span>
        <span class="article_description">{% trans 'HOT PLACE in Korea assembled' %}</span>
      </div> 

      <button 
        class="mr-6 text-base border border-gray-200 shadow hover:shadow-lg rounded-xl py-2 px-4"
        onclick="document.getElementById('searchChannel').style.display='block'">
        {% trans 'Search channel' %}
      </button>

      <div id="searchChannel" class="w3-modal">
        <div class="w3-modal-content rounded">
          <header class="w3-container bg-teal-300 rounded-t"> 
            <span onclick="document.getElementById('searchChannel').style.display='none'" 
            class="w3-button w3-display-topright rounded">&times;</span>
            <h4 class="text-teal-900 ml-3">{% trans 'Search channel' %}</h4>
          </header>
          <div class="w3-container">
            <form method="get" action="{% url 'restaurants:search-channels' %}" class="w-full py-6 flex flex-row">
                <input 
                    class="search-box border px-5 w-full text-gray-900 placeholder-gray-600 font-medium py-3 rounded-sm shadow-md hover:shadow-lg focus:outline-none" 
                    name="keyword" 
                    placeholder="{% trans 'Search with channel' %}" 
                >
                <button class="ml-4 mr-1"><i class="fas fa-search fa-2x"></i></button>
            </form> 
          </div>
        </div>
      </div>

    </div>

    <div class="flex flex-wrap mx-0 mb-10">
        
        {% if channels %}

            {% for channel in channels %}
                {% include 'mixins/channel_card.html' with channel=channel %}
            {% endfor %}

            
            {% include 'partials/adsense_horizontal.html' %}
            

        {% else %}  
        
            <div class="container mx-auto min-h-75vh flex flex-col items-center border-t mt-3 px-4">
    
                <div class="flex flex-col w-11/12 pt-16">
    
                    <span class="article_title ml-0 text-gray-600">                
                        <span class="font-bold text-red-600">"{{channel_name}}"</span>
                        {% trans 'no results.' %}
                    </span>           
                    <span class="article_description ml-0">• {% trans 'Make sure you enter the word correctly.' %}</span>
                    <span class="article_description ml-0">• {% trans 'Search with channel name.' %}</span>
                    <span class="article_description ml-0">• {% trans 'Search results sometimes can be inaccurate when spacing.' %}</span>
                </div>

                {% include 'mixins/no_results.html' %}

                {% include 'partials/adsense_horizontal.html' %}

            </div>

        {% endif %}

    </div>
    
  </div>
 

{% endblock content %}

templates/restaurants/channel_view.html
{% extends 'base.html' %} 
{% load i18n %} 
{% block page_title %}{% trans 'Channel list' %} {% endblock page_title %} 
{% block page_subject %}{% for c in channels.object_list %}{{c}} {% endfor %}| 방문한 맛집을 모아서 아!맛나에서 지도를 제공하는 채널입니다. {% endblock page_subject %}
{% block page_description %}아!맛나에서 맛집 지도를 제공하기 위한 채널들 입니다. ({% for c in channels.object_list %}{{c}} {% endfor %}){% endblock page_description %}
{% block page_keywords %}{% for c in channels.object_list %}{{c}},{{c}} 맛집지도,{% endfor %}맛집,TV맛집,먹방,맛집탐방{% endblock page_keywords %}    
{% block page_og_url %}restaurants/channel{% endblock page_og_url %}
{% block page_og_title %}{% trans 'Channel list' %} {% endblock page_og_title %}
{% block page_og_description %}아!맛나에서 맛집 지도를 제공하기 위한 채널들 입니다. ({% for c in channels.object_list %}{{c}} {% endfor %}){% endblock page_og_description %}
{% block page_og_image %}static/img/logo_square.png{% endblock page_og_image %}
    

{% block content %} 
    <div class="container mx-auto">

        {% include 'restaurants/channel_list.html' %}
        
    </div>

    <div class="flex item-center justify-center font-medium text-base sm:text-lg mb-20"> 

        {% if channels.has_previous %}
        <a href="?page={{channels.number|add:-1}}" class="text-teal-500">
            <i class="fas fa-arrow-left fa-lg"></i>
        </a>
        {% endif %}
        
        <span class="mx-3">
        {% blocktrans with current_page=channels.number total_pages=channels.paginator.num_pages %}Page {{current_page}} of {{total_pages}}{% endblocktrans %}
        </span>

        {% if channels.has_next %}
        <a href="?page={{channels.number|add:1}}" class="text-teal-500">
            <i class="fas fa-arrow-right fa-lg"></i>
        </a>
        {% endif %}
        
    </div>

    {% include 'partials/adsense_horizontal.html' %}
      
{% endblock content %}

templates/restaurants/home.html
{% extends 'base.html' %} 
{% load i18n %} 
{% block page_name %} 
Home 
{% endblock page_name %} 

{% block content %} 


  {% for c in channels %}
    <a href="#">
      <img src="{{c.thumbnail.url}}"/>
      <img src="{{c.image.url}}"/>
      <h1>{{c.name}} / {{c.description}} / {{c.pk}}</h1>
    </a>
  {% endfor %}
    
  {% for r in restaurants.object_list %}
      <div>
        <a href="{% url "restaurants:detail" r.pk %}">
          {{r.title}}
        </a>        
      </div>
  {% endfor %}  


  <h4>
    {% if restaurants.has_previous %}
      <a href="?page={{restaurants.number|add:-1}}">Previous</a>
    {% endif %}
    
    Page {{restaurants.number}} of {{restaurants.paginator.num_pages}}
    
    {% if restaurants.has_next %}
      <a href="?page={{restaurants.number|add:1}}">Next</a>
    {% endif %}
    
  </h4>
  </h6>
    {% for page in restaurants.paginator.page_range %}
      <a href="?page={{page}}">{{page}}</a>
    {% endfor %}
  </h6>
    

{% endblock content %}

templates/restaurants/main.html
{% extends 'base.html' %} 
{% load i18n %} 
{% block page_title %}{% trans 'ENJOY your meal in Korea with Amatna' %} {% endblock page_title %} 
{% block page_subject %}TV 방영 맛집, 크리에이터의 생생한 동영상으로 맛집을 찾아보세요. 아!맛나는 각 채널의 맛집 지도를 제공해 드립니다.{% endblock page_subject %}
{% block page_description %}맛집 광고 없는 맛집 서비스. TV에 나온 맛집, 먹방 크리에이터가 다녀온 맛집을 한눈에 볼 수 있도록 맛집지도를 제공합니다.{% endblock page_description %}
{% block page_keywords %}{% for c in channels %}{{c}},{{c}} 맛집지도,{% endfor %}맛집,TV맛집,먹방,맛집탐방{% endblock page_keywords %}    
{% block page_og_url %}{% endblock page_og_url %}
{% block page_og_title %}{% trans 'ENJOY your meal in Korea with Amatna' %} {% endblock page_og_title %}
{% block page_og_description %}맛집 광고 없는 맛집 서비스. TV에 나온 맛집, 먹방 크리에이터가 다녀온 맛집을 한눈에 볼 수 있도록 맛집지도를 제공합니다.{% endblock page_og_description %}
{% block page_og_image %}static/img/logo_square.png{% endblock page_og_image %}



{% block content %} 
  <div class="container mx-auto pb-10">

    <div class="flex sm:hidden w-full justify-center -mt-4">
      <div class="w-11/12 mb-12">
        {% include 'partials/search_bar.html' %}
      </div>
    </div>

    {% include 'restaurants/channel_list.html' %}

    {% include 'partials/adsense_horizontal.html' %}


    
    <div class="w-full pt-10">
      <div class=" pt-12 mb-10 flex flex-col w-11/12">
        <span class="article_title">{% trans 'Last Updated Restaurants' %}</span>
        <span class="article_sub">{% trans 'Videos is better than reviews' %}</span>
        <span class="article_description">{% trans 'Do not search reviews' %}</span>
        <span class="article_description">{% trans 'Watch mukbang in Korean Creators' %}</span>
      </div> 

      {% include 'restaurants/restaurant_list.html' %}
      
    </div>      


    <div class="bg-gray-100 sm:rounded-lg py-6 my-20">
      <div class="py-1 sm:w-3/5 align-middle mb-10">
          <span class="article_title">{% trans 'Search with category' %}<br></span>
          <span class="article_description">{% trans 'Search for the menu you want to eat.' %}</span>
      </div>
      <div class="px-6">
        {% for c in all_categories %}
          {% include 'mixins/categories.html' %}
        {% endfor %}
      </div>
      
    </div>

    {% include 'partials/adsense_horizontal.html' %}
    <div class="mb-16"></div>

  </div>
{% endblock content %}

templates/restaurants/restaurant_list.html
{% load i18n %} 
{% block content %} 

  <div class="container mx-auto pb-10">

    <div class="flex flex-wrap mx-0 mb-10">
        {% for restaurant in restaurants.object_list %}
          {% include 'mixins/restaurant_card.html' with restaurant=restaurant youtube=restaurant.youtube.all|first %}
        {% endfor %}
    </div> 

  </div>
  
  <div class="flex item-center justify-center font-medium text-base sm:text-lg mb-10"> 

    {% if restaurants.has_previous %}
      <a href="?page={{restaurants.number|add:-1}}" class="text-teal-500">
        <i class="fas fa-arrow-left fa-lg"></i>
      </a>
    {% endif %}
    
    <span class="mx-3">
      {% blocktrans with current_page=restaurants.number total_pages=restaurants.paginator.num_pages %}Page {{current_page}} of {{total_pages}}{% endblocktrans %}
    </span>

    {% if restaurants.has_next %}
      <a href="?page={{restaurants.number|add:1}}" class="text-teal-500">
        <i class="fas fa-arrow-right fa-lg"></i>
      </a>
    {% endif %}
    
  </div>

  {% include 'partials/adsense_horizontal.html' %}
  

{% endblock content %}

templates/restaurants/restaurant_upload.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <title>아!맛나 음식점_업로드</title>
  </head>
  <body>
    {% if messages %} 
        {% for message in messages %}
            <div>
                <!--                | means OR operator-->
                <strong>{{message|safe}}</strong>
            </div>
        {% endfor %} 
    {% else %} 
        {{order}}
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="file1"> Upload a file</label>
            <input type="file" id="file1" name="file" />
            <small>Only accepts CSV files</small>
            <button type="submit">Upload</button>
        </form>
    {% endif %} 
  </body>
</html>

templates/restaurants/search.html
{% extends 'base.html' %}
{% load i18n static %}
{% block page_title %}{% if tag %}{{tag}} {% trans 'Search results' %} {% elif channel%}{{channel}} {% trans 'Search results' %} {% elif category%}{{category}} {% trans 'Search results' %} {% endif %}{% endblock page_title %}
{% block page_description %}{% if tag %}{{tag}} {% trans 'Search results' %} - {% for r in restaurants.object_list %}{{r}}: {% for t in r.tag_set.all %}{{t}}, {% endfor %}{% endfor %}TV방영, 크리에이터 맛집 아!맛나{% elif channel%}{{channel}} {% trans 'Search results' %} - {% for r in restaurants.object_list %}{{r}}: {% for t in r.tag_set.all %}{{t}}, {% endfor %}{% endfor %}TV방영, 크리에이터 맛집 아!맛나{% elif category%}{{category}} {% trans 'Search results' %} - {% for r in restaurants.object_list %}{{r}}: {% for t in r.tag_set.all %}{{t}}, {% endfor %}{% endfor %}{% endif %}TV방영, 크리에이터 맛집 아!맛나{% endblock page_description %}
{% block page_subject %}아!맛나 검색결과 | TV에 방영된 맛집의 맛집 지도, 크리에이터의 맛집 지도를 확인해 보세요.{% endblock page_subject %}
{% block page_keywords %}{% for r in restaurants.object_list %}{{r}},{% for t in r.tag_set.all %}{{t}},{% endfor %}{% endfor %}{% endblock page_keywords %}    
{% block page_og_url %}{% if tag %}restaurants/search/?tag_set={{tag}}{% elif channel%}restaurants/channel/{{channel}}/{% elif category%}restaurants/category/{{category}}/{% endif %}{% endblock page_og_url %}
{% block page_og_title %}{% if tag %}{{tag}} {% trans 'Search results' %} {% elif channel%}{{channel}} {% trans 'Search results' %} {% elif category%}{{category}} {% trans 'Search results' %} {% endif %}{% endblock page_og_title %}
{% block page_og_description %}{% if tag %}TV에 방영 맛집, 크리에이터 맛집 지도 아!맛나 : '{{tag}}' {% trans 'Search results' %}{% elif channel %}TV에 방영 맛집, 크리에이터 맛집 검색 아!맛나 : '{{channel}}' {% trans 'Search results' %} - 맛집지도를 확인하세요.{% elif category %}TV에 방영 맛집, 크리에이터 맛집 지도 아!맛나 : '{{category}}' {% trans 'Search results' %}{% endif %}{% endblock page_og_description %}
{% block page_og_image %}{% if tag %}static/img/logo_square.png{% elif channel%}uploads/{{channel.image}}{% elif category%}static/img/logo_square.png{% endif %}{% endblock page_og_image %}


{% block search-bar %}    
{% endblock search-bar %}

{% block content %}


    

{% if restaurants.object_list.count > 0 %}
    <div class="container mx-auto -mt-4 sm:mt-0">        

        {% if tag %}
            <div class="p-1 w-11/12 lg:w-3/5 align-middle py-5">
                <span class="article_title text-gray-800 ml-3"><span class="text-red-500 mr-3">"{{tag}}"</span>{% trans 'Search Results' %}</span>
            </div>

        {% elif channel %}
            <div class="p-1 w-11/12 lg:w-3/5 align-middle py-5">
                <span class="article_title text-gray-800 ml-3"><span class="text-red-500 mr-3">"{{channel}}"</span>{% trans 'Search Results with Channel' %}</span>
            </div>
            <div class="bg-gray-200 sm:rounded-lg p-4 mt-4 flex flex-row">
                {% include 'mixins/channel_card.html' with channel=channel %}
            </div>

        {% elif category %}
            <div class="p-1 w-11/12 lg:w-3/5 align-middle py-5">
                <span class="article_title text-gray-800 ml-3"><span class="text-red-500 mr-3">"{{category}}"</span>{% trans 'Search Results with Category' %}</span>
            </div>
            <div class="bg-gray-100 sm:rounded-lg px-6 py-8 mt-4 sm:mt-0">
                <div class="p-1 w-11/12 lg:w-3/5 align-middle">
                    <span class="px-4 pb-8 -ml-3 font-normal text-lg block truncate text-gray-700">{% trans 'Search with another category' %}</span>
                </div>
                {% for c in all_categories %}
                        {% include 'mixins/categories.html' %}
                {% endfor %}
            </div>
        {% endif %}
    </div>
        
    <div class="container mx-auto pb-10">
        <div class="p-1 rounded-t-lg w-11/12 lg:w-3/5 align-middle">
            <span class="px-4 py-10 font-normal text-base sm:text-xl block text-gray-700 mt-4">
                {% blocktrans with total_restaurants=restaurants.object_list.count %}We searched {{total_restaurants}} restaurant(s){% endblocktrans %}
            </span>
        </div>
        <div class="w-full align-middle sm:rounded-t-lg flex flex-col sm:px-0 px-3">
            <span class="flex flex-row p-4 bg-orange-100 rounded-t-lg font-normal items-center justify-between text-base sm:text-xl truncate">
                <span>{% trans 'View List with Map' %}</span>
                <span class="flex flex-row items-center">
                    <button onclick="getLocation()"><img src="{% static 'img/my_location.png' %}" class="w-8 h-8 mr-3"></button>
                    <button onclick="setBounds()" class="outline-none hover:opacity-75 bg-red-500 px-4 rounded-md py-1 text-white sm:text-base text-sm">{% trans 'ALL' %}</button>
                </span>
            </span>
            <div id="map" style="width:100%;height:400px;" class="rounded-b-lg mb-16"></div>
            {% include 'mixins/map_marker.html' %}
        </div>               

        {% include 'partials/adsense_horizontal.html' %}
        <div class="mb-16"></div>


        <div class="w-full align-middle mb-6 sm:px-0 px-3">
            <span class="p-4 bg-orange-100 rounded-lg font-normal text-base sm:text-xl block truncate">{% trans 'List of Restaurants' %}</span>
        </div>     

        <div class="flex flex-wrap mx-0 mb-10">
            {% for restaurant in restaurants.object_list %}
                {% include 'mixins/restaurant_card.html' with restaurant=restaurant youtube=restaurant.youtube.all|first %}
            {% endfor %}
        </div>         
    </div>

    <div class="flex item-center justify-center font-medium text-base sm:text-lg mb-10"> 
    
        {% if restaurants.has_previous %}
        <a href="?page={{restaurants.number|add:-1}}" class="text-teal-500">
            <i class="fas fa-arrow-left fa-lg"></i>
        </a>
        {% endif %}
        
        <span class="mx-3">
        {% blocktrans with current_page=restaurants.number total_pages=restaurants.paginator.num_pages %}Page {{current_page}} of {{total_pages}}{% endblocktrans %}
        </span>
    
        {% if restaurants.has_next %}
        <a href="?page={{restaurants.number|add:1}}" class="text-teal-500">
            <i class="fas fa-arrow-right fa-lg"></i>
        </a>
        {% endif %}            
        
    </div>
        
    {% include 'partials/adsense_horizontal.html' %}

    <div class="mb-16"></div>

{% else %}

    <div class="container w-10/12 lg:3/5 mx-auto min-h-75vh flex flex-col items-center">
        {% if tag %}
            <div class="flex flex-col mt-12">
                <span class="article_title ml-0 text-gray-600">
                    <span class="font-bold text-red-600">"{{tag}}"</span>
                    {% trans 'There is no restaurant for this keyword' %}
                </span>
                <span class="article_description ml-0">• {% trans 'Make sure you enter the word correctly.' %}</span>
                <span class="article_description ml-0">• {% trans 'Please search for the local name and menu you want to find.' %}</span>
                <span class="article_description ml-0">• {% trans 'We do not support searching in English.' %}</span>
                <span class="article_description ml-0">• {% trans 'Please click image to recommend your favorite creator.' %}</span>
                <span class="article_description ml-0">• {% trans 'I will try harder so that everyone who visits can have a delicious day!' %}</span>
            </div>
        {% elif category %}
            <div class="flex flex-col mt-12">
                <span class="article_title ml-0 text-gray-600">
                    <span class="font-bold text-red-600">"{{category}}"</span>
                    {% trans 'There are no search results for the category.' %}
                </span>
                <span class="article_description ml-0">• {% trans 'Use the search box to find a restaurant.' %}</span>
                <span class="article_description ml-0">• {% trans 'Please search for the local name and menu you want to find.' %}</span>
                <span class="article_description ml-0">• {% trans 'We do not support searching in English.' %}</span>
                <span class="article_description ml-0">• {% trans 'Please click image to recommend your favorite creator.' %}</span>
                <span class="article_description ml-0">• {% trans 'I will try harder so that everyone who visits can have a delicious day!' %}</span>
            </div>

            <div class="bg-gray-100 rounded-lg px-6 py-6 mt-20">
                <div class="p-1 rounded-t-lg align-middle mb-10">
                    <span class="article_title ml-0">{% trans 'Search with another category' %}<br></span>
                    <span class="article_description ml-0">{% trans 'Search for the menu you want to eat.' %}</span>
                </div>
                {% for c in all_categories %}
                    {% include 'mixins/categories.html' %}
                {% endfor %}
            </div>
        {% endif %}
        
        {% include 'mixins/no_results.html' %}

    </div>
    
{% endif %}
{% endblock content %}

templates/restaurants/youtube_upload.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <title>아!맛나 유튜브 업로드 </title>
  </head>
  <body>
    {% if messages %} 
        {% for message in messages %}
            <div>
                <!--                | means OR operator-->
                <strong>{{message|safe}}</strong>
            </div>
        {% endfor %} 
    {% else %} 
        {{order}}
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="file1"> Upload a file</label>
            <input type="file" id="file1" name="file" />
            <small>Only accepts CSV files</small>
            <button type="submit">Upload</button>
        </form>
    {% endif %} 
  </body>
</html>