config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("restaurants/", include("restaurants.urls", namespace="restaurants")),
    path("users/", include("users.urls", namespace="users")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("youcandoit/", admin.site.urls),
    path("sentry-debug/", trigger_error),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from restaurants import views as restaurant_views
from django.views.generic import TemplateView

app_name = "core"
# include() 안에 namespace 를 사용하면 app_name 을 지정해 줘야 한다.(namespace = app_name)

urlpatterns = [
    path("", restaurant_views.main_views, name="home"),
    path(
        'robots.txt/',
        TemplateView.as_view(
            template_name="robots.txt", content_type='text/plain')),
    path(
        'ads.txt/',
        TemplateView.as_view(
            template_name="ads.txt", content_type='text/plain')),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
]

users/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser
from django.shortcuts import reverse
from core import managers as core_managers


class User(AbstractUser):
    """ Custom User Model """

    LOGIN_EMAIL = "email"
    LOGIN_KAKAO = "kakao"
    LOGIN_NAVER = "naver"
    LOGIN_FACEBOOK = "facebook"

    LOGIN_CHOICES = (
        (LOGIN_EMAIL, _("Email")),
        (LOGIN_KAKAO, _("Kakao")),
        (LOGIN_NAVER, _("Naver")),
        (LOGIN_FACEBOOK, _("Facebook")),
    )

    avatar = models.ImageField(_("avatar"), upload_to="avatars", blank=True)
    nickname = models.CharField(_("nickname"), max_length=20, default="")
    email_verified = models.BooleanField(_("email verified"), default=False)
    email_secret = models.CharField(
        _("email secret"), max_length=20, default="", blank=True
    )
    login_method = models.CharField(
        _("login method"), choices=LOGIN_CHOICES, max_length=50, default=LOGIN_EMAIL
    )
    objects = core_managers.CustomUserManager()

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

users/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from . import models


class LoginForm(forms.Form):

    email = forms.EmailField(
        label=_("Email"),
        widget=forms.EmailInput(attrs={"placeholder": _("Please enter your email.")}),
    )
    password = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(
            attrs={"placeholder": _("Please enter your password.")}
        ),
    )

    def clean(self):
        # 클린을 사용하면 그 필드에 직접 에러를 추가해주면 됨.
        # clean_password(), clean_username() 이렇데 할거면 그냥 error를 raise한면 됨
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
                # clean()을 썼다면 무조건 cleaned_data를 리턴해줘야 함
            else:
                self.add_error(
                    "password", forms.ValidationError(_("Password id wrong"))
                )
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError(_("User does not exist")))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ("email", "nickname")
        widgets = {
            "email": forms.TextInput(
                attrs={"placeholder": _("Please enter your email.")}
            ),
            "nickname": forms.TextInput(
                attrs={"placeholder": _("Please enter your nickname.")}
            ),
        }

    password = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(
            attrs={"placeholder": _("Please enter your password.")}
        ),
    )
    password1 = forms.CharField(
        label=_("Confirm password"),
        widget=forms.PasswordInput(
            attrs={"placeholder": _("Please confirm your password.")}
        ),
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError(
                _("User already exists with that email"), code="existing_user"
            )
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password != password1:
            raise forms.ValidationError(_("Password comfirmation does not match"))
        else:
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()

users/views.py
import os
import requests
from django.views.generic import FormView, DetailView, UpdateView
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy
from django.shortcuts import redirect, reverse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordChangeView
from django.core.files.base import ContentFile
from django.contrib.messages.views import SuccessMessageMixin
from . import forms, models, mixins


class LoginView(mixins.LoggedOutOnlyView, FormView):

    # FormView에서는 get이나 post를 쓰지 않는다.
    template_name = "users/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


def log_out(request):
    logout(request)
    messages.info(request, _("Bye bye :) See you soon."))
    return redirect(reverse("core:home"))


class SignUpView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)


def kakao_login(request):
    cilent_id = os.environ.get("KAKAO_KEY")
    redirect_uri = "https://amatna.net/users/login/kakao/callback"
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={cilent_id}&redirect_uri={redirect_uri}&response_type=code"
    )


class KakaoException(Exception):
    pass


def kakao_callback(request):
    try:
        code = request.GET.get("code")
        client_id = os.environ.get("KAKAO_KEY")
        redirect_uri = "https://amatna.net/users/login/kakao/callback"
        token_request = requests.get(
            f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&redirect_uri={redirect_uri}&code={code}"
        )
        token_json = token_request.json()
        error = token_json.get("error", None)
        if error is not None:
            raise KakaoException(_("Kakao authenfication is not completed"))
        access_token = token_json.get("access_token")
        profile_request = requests.get(
            "https://kapi.kakao.com/v2/user/me",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        profile_json = profile_request.json()
        kakao_account = profile_json.get("kakao_account")
        properties = profile_json.get("properties")
        email = kakao_account.get("email")
        nickname = properties.get("nickname")
        profile_image = properties.get("profile_image")
        try:
            user = models.User.objects.get(email=email)
            if user.login_method != models.User.LOGIN_KAKAO:
                raise KakaoException(_("Please log in with another method"))
        except models.User.DoesNotExist:
            user = models.User.objects.create(
                username=email,
                email=email,
                nickname=nickname,
                login_method=models.User.LOGIN_KAKAO,
                email_verified=True,
            )
            user.set_unusable_password()
            user.save()
            if profile_image is not None:
                photo_request = requests.get(profile_image)
                user.avatar.save(f"{nickname}-avatar",
                                 ContentFile(photo_request.content))
        login(request, user)
        return redirect(reverse("core:home"))
    except KakaoException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


class UserProfileView(DetailView):

    model = models.User
    context_object_name = "user_obj"


class UpdateProfileView(mixins.LoggedInOnlyView, SuccessMessageMixin,
                        UpdateView):
    model = models.User
    template_name = "users/update_profile.html"
    fields = ("nickname",)
    success_message = _("Your profile is edited")

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["nickname"].widget.attrs = {
            "label": _("Nickname"),
        }
        return form

    def get_object(self, queryset=None):
        return self.request.user


class UpdatePasswordView(
        PasswordChangeView,
        mixins.LoggedInOnlyView,
        mixins.EmailLoginOnlyView,
        SuccessMessageMixin,
):

    template_name = "users/update_password.html"
    success_message = _("Your password is changed")

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["old_password"].widget.attrs = {
            "placeholder": _("Enter current password"),
        }
        form.fields["new_password1"].widget.attrs = {
            "placeholder": _("Enter new password")
        }
        form.fields["new_password2"].widget.attrs = {
            "placeholder": _("Confirm new password")
        }
        return form

    def get_success_url(self):
        return self.request.user.get_absolute_url()

templates/users/login.html
{% extends 'base.html' %}
{% load i18n static %}
{% block page_title %}{% trans 'Login' %}{% endblock page_title %}
{% block page_subject %}아!맛나의 로그인 페이지 입니다.{% endblock page_subject %}
{% block page_keywords %}이태원맛집,홍대맛집,강남역맛집,가로수길맛집,신촌맛집,명동맛집,대학로맛집,연남동맛집,부산맛집,합정맛집,대구맛집,여의도맛집,건대맛집,광화문맛집,일산맛집,제주맛집,경리단길맛집,한남동맛집,삼청동맛집,대전맛집,종로맛집,서촌맛집,
잠실맛집,사당역맛집,인천맛집,코엑스맛집,상수맛집,서래마을맛집,송도맛집,왕십리맛집,분당맛집,혜화맛집,고속터미널맛집,맛집지도,TV맛집,맛집{% endblock page_keywords %}    
{% block page_og_url %}users/login/{% endblock page_og_url %}
{% block page_og_title %}{% trans 'Login' %} {% endblock page_og_title %}
{% block page_og_description %}TV 방영 맛집, 먹방 또는 맛집탐방 크리에이터가 다녀온 음식점들을 모아 맛집 지도를 만들어 드리는 아!맛나. 댓글 알바, 맛집 광고 nono! 크리에이터의 생생한 영상으로 맛집을 찾아보세요.{% endblock page_og_description %}
{% block page_og_image %}static/img/logo_square.png{% endblock page_og_image %}


{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container xl:w-1/3 lg:w-5/12 md:w-8/12 w-11/12 min-h-75vh mx-auto my-10 flex flex-col items-center p-6 b-20">

            <img src="{% static 'img/logo.png' %}" class="w-32 pt-8">
            <div class="article_description font-normal mt-10 mb-5 ml-0 text-red-600">{% trans '"The restaurant on my favorite Korean TV show."' %}</div>
            <div class="article_description font-normal mb-5 ml-0 text-red-600">{% trans '"The restaurant that my favorite Korean creator went to."' %}</div>
            <div class="article_description font-normal mb-5 ml-0">{% trans 'If you log in, you can save the restaurant you want to go to.' %}</div>
            <div class="article_description font-normal mb-10 ml-0">{% trans 'Gather the restaurants you want to go to on amatna' %}</div>

        {% include 'partials/social_login.html' %}


        {% include 'mixins/auth/auth_form.html' with form=form cta="로그인" %}

        <div class="mt-5">
            <span class="mr-3">{% trans 'Do not have an account?' %}</span>
            <a href="{% url 'users:signup' %}" class="font-medium text-teal-600">{% trans 'Sign up' %}</a>
        </div>        

    </div>


{% endblock content %}

templates/users/signup.html
{% extends 'base.html' %}
{% load i18n static %}
{% block page_title %}\{% trans 'Sign Up' %}{% endblock page_title %}
{% block page_description %}TV 방영 맛집, 먹방 또는 맛집탐방 크리에이터가 다녀온 음식점들을 모아 맛집 지도를 만들어 드리는 아!맛나. 댓글 알바, 맛집 광고 nono! 크리에이터의 생생한 영상으로 맛집을 찾아보세요.{% endblock page_description %}
{% block page_subject %}아!맛나의 회원가입 페이지 입니다.{% endblock page_subject %}
{% block page_keywords %}이태원맛집,홍대맛집,강남역맛집,가로수길맛집,신촌맛집,명동맛집,대학로맛집,연남동맛집,부산맛집,합정맛집,대구맛집,여의도맛집,건대맛집,광화문맛집,일산맛집,제주맛집,경리단길맛집,한남동맛집,삼청동맛집,대전맛집,종로맛집,서촌맛집,
잠실맛집,사당역맛집,인천맛집,코엑스맛집,상수맛집,서래마을맛집,송도맛집,왕십리맛집,분당맛집,혜화맛집,고속터미널맛집,맛집지도,TV맛집,맛집{% endblock page_keywords %}    
{% block page_og_url %}users/signup/{% endblock page_og_url %}
{% block page_og_title %}{% trans 'Sign Up' %} {% endblock page_og_title %}
{% block page_og_description %}TV 방영 맛집, 먹방 또는 맛집탐방 크리에이터가 다녀온 음식점들을 모아 맛집 지도를 만들어 드리는 아!맛나. 댓글 알바, 맛집 광고 nono! 크리에이터의 생생한 영상으로 맛집을 찾아보세요.{% endblock page_og_description %}
{% block page_og_image %}static/img/logo_square.png{% endblock page_og_image %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container xl:w-1/3 lg:w-5/12 md:w-8/12 w-11/12 min-h-75vh mx-auto my-10 flex flex-col items-center p-6 b-20">

    <img src="{% static 'img/logo.png' %}" class="w-32 pt-8">
    <div class="article_description font-normal mt-10 mb-5 ml-0 text-red-600">{% trans '"The restaurant on my favorite Korean TV show."' %}</div>
    <div class="article_description font-normal mb-5 ml-0 text-red-600">{% trans '"The restaurant that my favorite Korean creator went to."' %}</div>
    <div class="article_description font-normal mb-5 ml-0">{% trans 'If you sign up, you can save the restaurant you want to go to.' %}</div>
    <div class="article_description font-normal mb-10 ml-0">{% trans 'Gather the restaurants you want to go to on amatna' %}</div>


    {% include 'partials/social_login.html' %}

    {% include 'mixins/auth/auth_form.html' with form=form cta="회원가입" %}

    <div class="mt-5">
        <span class="mr-2">{% trans 'Have an account?' %}</span>
        <a href="{% url 'users:login' %}" class="text-teal-500 font-medium">{% trans 'Log in' %}</a>
    </div>

</div>


{% endblock content %}

templates/users/update_password.html
{% extends 'base.html' %}
{% load i18n %}
{% block page_title %}{% trans 'Change password' %}{% endblock page_title %}
{% block page_description %}TV 방영 맛집, 먹방 또는 맛집탐방 크리에이터가 다녀온 음식점들을 모아 맛집 지도를 만들어 드리는 아!맛나. 댓글 알바, 맛집 광고 nono! 크리에이터의 생생한 영상으로 맛집을 찾아보세요.{% endblock page_description %}
{% block page_subject %}아!맛나의 회원가입 페이지 입니다.{% endblock page_subject %}
{% block page_keywords %}이태원맛집,홍대맛집,강남역맛집,가로수길맛집,신촌맛집,명동맛집,대학로맛집,연남동맛집,부산맛집,합정맛집,대구맛집,여의도맛집,건대맛집,광화문맛집,일산맛집,제주맛집,경리단길맛집,한남동맛집,삼청동맛집,대전맛집,종로맛집,서촌맛집,
잠실맛집,사당역맛집,인천맛집,코엑스맛집,상수맛집,서래마을맛집,송도맛집,왕십리맛집,분당맛집,혜화맛집,고속터미널맛집,맛집지도,TV맛집,맛집{% endblock page_keywords %}    
{% block page_og_url %}users/update-password/{% endblock page_og_url %}
{% block page_og_title %}{% trans 'Change password' %} {% endblock page_og_title %}
{% block page_og_description %}TV 방영 맛집, 먹방 또는 맛집탐방 크리에이터가 다녀온 음식점들을 모아 맛집 지도를 만들어 드리는 아!맛나. 댓글 알바, 맛집 광고 nono! 크리에이터의 생생한 영상으로 맛집을 찾아보세요.{% endblock page_og_description %}
{% block page_og_image %}static/img/logo_square.png{% endblock page_og_image %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="min-h-50vh">
        <div class="container px-6 w-11/12 lg:w-1/3 md:w-2/5 container mx-auto my-10 flex flex-col rounded-xl shadow-xl items-center border p-10 b-20 border-gray-100">

            {% include 'mixins/auth/auth_form.html' with form=form cta="비밀번호 변경" %}

        </div>
    </div>

    {% include 'partials/adsense_horizontal.html' %}

{% endblock content %}

templates/users/update_profile.html
{% extends 'base.html' %}
{% load i18n %}
{% block page_title %}{% trans 'Modify profile' %}{% endblock page_title %}
{% block page_description %}TV 방영 맛집, 먹방 또는 맛집탐방 크리에이터가 다녀온 음식점들을 모아 맛집 지도를 만들어 드리는 아!맛나. 댓글 알바, 맛집 광고 nono! 크리에이터의 생생한 영상으로 맛집을 찾아보세요.{% endblock page_description %}
{% block page_subject %}아!맛나의 회원가입 페이지 입니다.{% endblock page_subject %}
{% block page_keywords %}이태원맛집,홍대맛집,강남역맛집,가로수길맛집,신촌맛집,명동맛집,대학로맛집,연남동맛집,부산맛집,합정맛집,대구맛집,여의도맛집,건대맛집,광화문맛집,일산맛집,제주맛집,경리단길맛집,한남동맛집,삼청동맛집,대전맛집,종로맛집,서촌맛집,
잠실맛집,사당역맛집,인천맛집,코엑스맛집,상수맛집,서래마을맛집,송도맛집,왕십리맛집,분당맛집,혜화맛집,고속터미널맛집,맛집지도,TV맛집,맛집{% endblock page_keywords %}    
{% block page_og_url %}users/update-profile/{% endblock page_og_url %}
{% block page_og_title %}{% trans 'Modify profile' %} {% endblock page_og_title %}
{% block page_og_description %}TV 방영 맛집, 먹방 또는 맛집탐방 크리에이터가 다녀온 음식점들을 모아 맛집 지도를 만들어 드리는 아!맛나. 댓글 알바, 맛집 광고 nono! 크리에이터의 생생한 영상으로 맛집을 찾아보세요.{% endblock page_og_description %}
{% block page_og_image %}static/img/logo_square.png{% endblock page_og_image %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="min-h-50vh">

        <div class="container px-6 w-11/12 lg:w-1/3 md:w-2/5 container mx-auto my-10 flex flex-col rounded-xl shadow-xl items-center border p-10 b-20 border-gray-100">
    
            {% include 'mixins/auth/auth_form.html' with form=form cta="프로필 수정" %}
    
            {% if object.login_method == "email" %}
                <div class="mt-5">
                    <a href="{% url 'users:password' %}" class="font-medium text-teal-600">{% trans 'Change password' %}</a>
                </div>        
            {% endif %}

        </div>
    </div>

    {% include 'partials/adsense_horizontal.html' %}


{% endblock content %} 

templates/users/user_detail.html
{% extends 'base.html' %}
{% load i18n static %}
{% block page_title %}{{user_obj.nickname}}님의 프로필{% endblock page_title %}
{% block page_description %}TV 방영 맛집, 먹방 또는 맛집탐방 크리에이터가 다녀온 음식점들을 모아 맛집 지도를 만들어 드리는 아!맛나. 댓글 알바, 맛집 광고 nono! 크리에이터의 생생한 영상으로 맛집을 찾아보세요.{% endblock page_description %}
{% block page_subject %}아!맛나의 프로필 페이지 입니다.{% endblock page_subject %}
{% block page_keywords %}이태원맛집,홍대맛집,강남역맛집,가로수길맛집,신촌맛집,명동맛집,대학로맛집,연남동맛집,부산맛집,합정맛집,대구맛집,여의도맛집,건대맛집,광화문맛집,일산맛집,제주맛집,경리단길맛집,한남동맛집,삼청동맛집,대전맛집,종로맛집,서촌맛집,
잠실맛집,사당역맛집,인천맛집,코엑스맛집,상수맛집,서래마을맛집,송도맛집,왕십리맛집,분당맛집,혜화맛집,고속터미널맛집,맛집지도,TV맛집,맛집{% endblock page_keywords %}    
{% block page_og_url %}{% endblock page_og_url %}
{% block page_og_title %}{% trans 'ENJOY your meal in Korea with Amatna' %} {% endblock page_og_title %}
{% block page_og_description %}TV 방영 맛집, 먹방 또는 맛집탐방 크리에이터가 다녀온 음식점들을 모아 맛집 지도를 만들어 드리는 아!맛나. 댓글 알바, 맛집 광고 nono! 크리에이터의 생생한 영상으로 맛집을 찾아보세요.{% endblock page_og_description %}
{% block page_og_image %}static/img/logo_square.png{% endblock page_og_image %}


{% block content %}

    <div class="min-h-50vh">        
        <div class="container px-6 w-11/12 lg:w-1/3 md:w-2/5 container mx-auto my-10 flex flex-col rounded-xl shadow-xl items-center border p-10 b-20 border-gray-100">
            {% include 'mixins/user_avatar.html' with user=user_obj %}
            
            <div class="flex items-center text-gray-700 px-10">
                <span class="text-lg py-10">{{user_obj.username}}</span>
                {% if user_obj.login_method == "kakao" %}
                    <img src="{% static 'img/kakao_logo.png' %}" class="ml-3 w-10 h-10">
                {% endif %}         
            </div>
            <div class="flex flex-row justify-center w-full mb-16 px-10">
                <span class="text-2xl font-normal py-1 mr-5">{{user_obj.nickname}}</span>
                <a href="{% url 'users:update' %}"><i class="far fa-edit fa-2x text-gray-700 py-1"></i></a>
            </div>
            <a href="{% url 'users:logout' %}" class="btn-link w-full">{% trans 'Log out' %}</a>
        </div>
        
    </div>
    
    {% include 'partials/adsense_horizontal.html' %}

{% endblock content %}